name: websocket_test
description: A sample command-line application.
version: 0.0.1
#homepage: https://www.nullpointerbay.com
#author: charafau <gorudonbu@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
